version: "3"
services:
  python-server:
    container_name: python-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"

  redis:
    container_name: redis-python
    image: redis:alpine
    ports:
      - "6379:6379"
